### ISSUE TITLE
CMake and Code Improvements

### ISSUE THREAD

**Issue by yazdanbhd** [403unlocker/best403unlocker-gui#1]
There are several areas in the project that could benefit from enhancements in both the CMake setup and the code itself. Below are the suggested improvements:

## CMake Improvements

1. **Specify C++ version**: 
   - Explicitly set the C++ standard in your CMakeLists.txt file.

2. **Modernize package finding**:
   - Replace `pkg_check_modules` with `find_package` or use `PkgConfig::` imported targets.
   - Update your linking command to:
     ```cmake
     target_link_libraries(${PROJECT_NAME} PRIVATE libcurl PkgConfig::GTKMM)
     ```

3. **Explicit source file listing**:
   - Replace `file(GLOB)` with explicit listing of source files to ensure CMake picks up new files correctly.

4. **Cross-platform support**:
   - Enhance CMake configuration to handle macOS and Windows platforms in addition to Linux.

5. **Proper c-ares integration**:
   - Use `FetchContent` to include `c-ares` since `libcurl` uses it when `ENABLE_ARES` is set to `ON`.

## Code Improvements

1. **Replace NULL with nullptr**:
   - Use `nullptr` instead of `NULL` throughout the codebase for improved type safety.

2. **RAII for CURL handle**:
   - Wrap CURL handle in a smart pointer or custom RAII class for exception safety.

3. **Use static_cast**:
   - Replace C-style casts with `static_cast` for improved type safety.

4. **Utilize smart pointers**:
   - Implement smart pointers for dynamically allocated objects to ensure automatic resource cleanup and exception safety.

**Comment by ghost** [comment]
Thanks for opening this issue.
I applied the **CMake Improvements** on the project. Can you open a pull request and apply **Code Improvements** to the updated source code?
